### ISSUE TITLE
Players need more than +2 and -2 valuations

### ISSUE THREAD

**Issue by connormcmk** [optionhq/index-wallets-game#35] opened 2024-07-31 03:53 UTC
Player ended up with a -3 valuation but they would make it smaller if it were easier.

The natural way to do this would be with the player's valuation centered on the bar, and then scrolling the bar would move everyone else's valuation and keep theirs in the center of the bar with a number on top.

**Comment by volkyeth** [comment] 2024-07-31 17:39
The problem with that approach is that the user then can't discern other players' valuations (It somewhat suffers from that already because of the overlapping markers)

Will have to rethink that UI

**Comment by cnrmck** [comment] 2024-07-31 18:52
Why can't they discern other players' valuations?

**Comment by volkyeth** [comment] 2024-08-20 19:47
Duplicate of #51

**Closed** 2024-08-20 19:47 UTC
